// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProposeServiceV1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Casper.V1 {
  public static partial class ProposeService
  {
    static readonly string __ServiceName = "casper.v1.ProposeService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Casper.PrintUnmatchedSendsQuery> __Marshaller_casper_PrintUnmatchedSendsQuery = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Casper.PrintUnmatchedSendsQuery.Parser));
    static readonly grpc::Marshaller<global::Casper.V1.ProposeResponse> __Marshaller_casper_v1_ProposeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Casper.V1.ProposeResponse.Parser));

    static readonly grpc::Method<global::Casper.PrintUnmatchedSendsQuery, global::Casper.V1.ProposeResponse> __Method_propose = new grpc::Method<global::Casper.PrintUnmatchedSendsQuery, global::Casper.V1.ProposeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "propose",
        __Marshaller_casper_PrintUnmatchedSendsQuery,
        __Marshaller_casper_v1_ProposeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Casper.V1.ProposeServiceV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ProposeService</summary>
    [grpc::BindServiceMethod(typeof(ProposeService), "BindService")]
    public abstract partial class ProposeServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Casper.V1.ProposeResponse> propose(global::Casper.PrintUnmatchedSendsQuery request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ProposeService</summary>
    public partial class ProposeServiceClient : grpc::ClientBase<ProposeServiceClient>
    {
      /// <summary>Creates a new client for ProposeService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProposeServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ProposeService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProposeServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProposeServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProposeServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Casper.V1.ProposeResponse propose(global::Casper.PrintUnmatchedSendsQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return propose(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Casper.V1.ProposeResponse propose(global::Casper.PrintUnmatchedSendsQuery request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_propose, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Casper.V1.ProposeResponse> proposeAsync(global::Casper.PrintUnmatchedSendsQuery request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return proposeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Casper.V1.ProposeResponse> proposeAsync(global::Casper.PrintUnmatchedSendsQuery request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_propose, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProposeServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProposeServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProposeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_propose, serviceImpl.propose).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ProposeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_propose, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Casper.PrintUnmatchedSendsQuery, global::Casper.V1.ProposeResponse>(serviceImpl.propose));
    }

  }
}
#endregion
