// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: routing.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Routing {
  public static partial class TransportLayer
  {
    static readonly string __ServiceName = "routing.TransportLayer";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Routing.TLRequest> __Marshaller_routing_TLRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Routing.TLRequest.Parser));
    static readonly grpc::Marshaller<global::Routing.TLResponse> __Marshaller_routing_TLResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Routing.TLResponse.Parser));
    static readonly grpc::Marshaller<global::Routing.Chunk> __Marshaller_routing_Chunk = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Routing.Chunk.Parser));

    static readonly grpc::Method<global::Routing.TLRequest, global::Routing.TLResponse> __Method_Send = new grpc::Method<global::Routing.TLRequest, global::Routing.TLResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Send",
        __Marshaller_routing_TLRequest,
        __Marshaller_routing_TLResponse);

    static readonly grpc::Method<global::Routing.Chunk, global::Routing.TLResponse> __Method_Stream = new grpc::Method<global::Routing.Chunk, global::Routing.TLResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "Stream",
        __Marshaller_routing_Chunk,
        __Marshaller_routing_TLResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Routing.RoutingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TransportLayer</summary>
    [grpc::BindServiceMethod(typeof(TransportLayer), "BindService")]
    public abstract partial class TransportLayerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Routing.TLResponse> Send(global::Routing.TLRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Routing.TLResponse> Stream(grpc::IAsyncStreamReader<global::Routing.Chunk> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TransportLayer</summary>
    public partial class TransportLayerClient : grpc::ClientBase<TransportLayerClient>
    {
      /// <summary>Creates a new client for TransportLayer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TransportLayerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TransportLayer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TransportLayerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TransportLayerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TransportLayerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Routing.TLResponse Send(global::Routing.TLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Send(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Routing.TLResponse Send(global::Routing.TLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Routing.TLResponse> SendAsync(global::Routing.TLRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Routing.TLResponse> SendAsync(global::Routing.TLRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Send, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Routing.Chunk, global::Routing.TLResponse> Stream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Routing.Chunk, global::Routing.TLResponse> Stream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_Stream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TransportLayerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TransportLayerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TransportLayerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Send, serviceImpl.Send)
          .AddMethod(__Method_Stream, serviceImpl.Stream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TransportLayerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Send, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Routing.TLRequest, global::Routing.TLResponse>(serviceImpl.Send));
      serviceBinder.AddMethod(__Method_Stream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::Routing.Chunk, global::Routing.TLResponse>(serviceImpl.Stream));
    }

  }
}
#endregion
