// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: CasperMessage.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Casper
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HasBlockRequestProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HasBlockProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockRequestProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ForkChoiceTipRequestProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApprovedBlockCandidateProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"block")]
        public BlockMessageProto Block { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int requiredSigs { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnapprovedBlockProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"candidate")]
        public ApprovedBlockCandidateProto Candidate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"duration")]
        public long Duration { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Signature : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] publicKey { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"algorithm")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Algorithm { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"sig")]
        public byte[] Sig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockApprovalProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"candidate")]
        public ApprovedBlockCandidateProto Candidate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sig")]
        public Signature Sig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApprovedBlockProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"candidate")]
        public ApprovedBlockCandidateProto Candidate { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sigs")]
        public global::System.Collections.Generic.List<Signature> Sigs { get; } = new global::System.Collections.Generic.List<Signature>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApprovedBlockRequestProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Identifier { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public bool trimState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NoApprovedBlockAvailableProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"identifier")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Identifier { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nodeIdentifer { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockMessageProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] blockHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"header")]
        public HeaderProto Header { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"body")]
        public BodyProto Body { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"justifications")]
        public global::System.Collections.Generic.List<JustificationProto> Justifications { get; } = new global::System.Collections.Generic.List<JustificationProto>();

        [global::ProtoBuf.ProtoMember(5, Name = @"sender")]
        public byte[] Sender { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int seqNum { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"sig")]
        public byte[] Sig { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sigAlgorithm { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string shardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10)]
        public byte[] extraBytes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockHashMessageProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] blockCreator { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockMetadataInternal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] blockHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parents")]
        public global::System.Collections.Generic.List<byte[]> Parents { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(3, Name = @"sender")]
        public byte[] Sender { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"justifications")]
        public global::System.Collections.Generic.List<JustificationProto> Justifications { get; } = new global::System.Collections.Generic.List<JustificationProto>();

        [global::ProtoBuf.ProtoMember(5, Name = @"bonds")]
        public global::System.Collections.Generic.List<BondProto> Bonds { get; } = new global::System.Collections.Generic.List<BondProto>();

        [global::ProtoBuf.ProtoMember(6)]
        public long blockNum { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public int seqNum { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"invalid")]
        public bool Invalid { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HeaderProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"parentsHashList")]
        public global::System.Collections.Generic.List<byte[]> parentsHashLists { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(5, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"version")]
        public long Version { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public byte[] extraBytes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeployDataProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"deployer")]
        public byte[] Deployer { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"term")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Term { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sig")]
        public byte[] Sig { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sigAlgorithm { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public long phloPrice { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long phloLimit { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public long validAfterBlockNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessedDeployProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"deploy")]
        public DeployDataProto Deploy { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cost")]
        public global::dotrchain.PCost Cost { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"deployLog")]
        public global::System.Collections.Generic.List<EventProto> deployLogs { get; } = new global::System.Collections.Generic.List<EventProto>();

        [global::ProtoBuf.ProtoMember(5, Name = @"errored")]
        public bool Errored { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string systemDeployError { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SlashSystemDeployDataProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] invalidBlockHash { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] issuerPublicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CloseBlockSystemDeployDataProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SystemDeployDataProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SlashSystemDeployDataProto slashSystemDeploy
        {
            get => __pbn__systemDeploy.Is(1) ? ((SlashSystemDeployDataProto)__pbn__systemDeploy.Object) : default;
            set => __pbn__systemDeploy = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeslashSystemDeploy() => __pbn__systemDeploy.Is(1);
        public void ResetslashSystemDeploy() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__systemDeploy, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__systemDeploy;

        [global::ProtoBuf.ProtoMember(2)]
        public CloseBlockSystemDeployDataProto closeBlockSystemDeploy
        {
            get => __pbn__systemDeploy.Is(2) ? ((CloseBlockSystemDeployDataProto)__pbn__systemDeploy.Object) : default;
            set => __pbn__systemDeploy = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializecloseBlockSystemDeploy() => __pbn__systemDeploy.Is(2);
        public void ResetcloseBlockSystemDeploy() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__systemDeploy, 2);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessedSystemDeployProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SystemDeployDataProto systemDeploy { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"deployLog")]
        public global::System.Collections.Generic.List<EventProto> deployLogs { get; } = new global::System.Collections.Generic.List<EventProto>();

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string errorMsg { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BodyProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"state")]
        public RChainStateProto State { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"deploys")]
        public global::System.Collections.Generic.List<ProcessedDeployProto> Deploys { get; } = new global::System.Collections.Generic.List<ProcessedDeployProto>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ProcessedSystemDeployProto> systemDeploys { get; } = new global::System.Collections.Generic.List<ProcessedSystemDeployProto>();

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] extraBytes { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JustificationProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"validator")]
        public byte[] Validator { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] latestBlockHash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RChainStateProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] preStateHash { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] postStateHash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"bonds")]
        public global::System.Collections.Generic.List<BondProto> Bonds { get; } = new global::System.Collections.Generic.List<BondProto>();

        [global::ProtoBuf.ProtoMember(4)]
        public long blockNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"produce")]
        public ProduceEventProto Produce
        {
            get => __pbn__event_instance.Is(1) ? ((ProduceEventProto)__pbn__event_instance.Object) : default;
            set => __pbn__event_instance = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeProduce() => __pbn__event_instance.Is(1);
        public void ResetProduce() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event_instance, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__event_instance;

        [global::ProtoBuf.ProtoMember(2, Name = @"consume")]
        public ConsumeEventProto Consume
        {
            get => __pbn__event_instance.Is(2) ? ((ConsumeEventProto)__pbn__event_instance.Object) : default;
            set => __pbn__event_instance = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeConsume() => __pbn__event_instance.Is(2);
        public void ResetConsume() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event_instance, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"comm")]
        public CommEventProto Comm
        {
            get => __pbn__event_instance.Is(3) ? ((CommEventProto)__pbn__event_instance.Object) : default;
            set => __pbn__event_instance = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeComm() => __pbn__event_instance.Is(3);
        public void ResetComm() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__event_instance, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProduceEventProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] channelsHash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"persistent")]
        public bool Persistent { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int timesRepeated { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsumeEventProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<byte[]> channelsHashes { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(2, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"persistent")]
        public bool Persistent { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommEventProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consume")]
        public ConsumeEventProto Consume { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"produces")]
        public global::System.Collections.Generic.List<ProduceEventProto> Produces { get; } = new global::System.Collections.Generic.List<ProduceEventProto>();

        [global::ProtoBuf.ProtoMember(3, Name = @"peeks")]
        public global::System.Collections.Generic.List<PeekProto> Peeks { get; } = new global::System.Collections.Generic.List<PeekProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PeekProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int channelIndex { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BondProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"validator")]
        public byte[] Validator { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stake")]
        public long Stake { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreNodeKeyProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        public byte[] Hash { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"index")]
        public int Index { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreItemsMessageRequestProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"startPath")]
        public global::System.Collections.Generic.List<StoreNodeKeyProto> startPaths { get; } = new global::System.Collections.Generic.List<StoreNodeKeyProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"skip")]
        public int Skip { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"take")]
        public int Take { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreItemProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public byte[] Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public byte[] Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StoreItemsMessageProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"startPath")]
        public global::System.Collections.Generic.List<StoreNodeKeyProto> startPaths { get; } = new global::System.Collections.Generic.List<StoreNodeKeyProto>();

        [global::ProtoBuf.ProtoMember(2, Name = @"lastPath")]
        public global::System.Collections.Generic.List<StoreNodeKeyProto> lastPaths { get; } = new global::System.Collections.Generic.List<StoreNodeKeyProto>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<StoreItemProto> historyItems { get; } = new global::System.Collections.Generic.List<StoreItemProto>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<StoreItemProto> dataItems { get; } = new global::System.Collections.Generic.List<StoreItemProto>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
