// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: DeployServiceCommon.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Casper
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FindDeployQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] deployId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Hash { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlocksQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depth")]
        public int Depth { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlocksQueryByHeight : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long startBlockNumber { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long endBlockNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DataAtNameQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depth")]
        public int Depth { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        public global::dotrchain.Par Name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContinuationAtNameQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depth")]
        public int Depth { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"names")]
        public global::System.Collections.Generic.List<global::dotrchain.Par> Names { get; } = new global::System.Collections.Generic.List<global::dotrchain.Par>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VisualizeDagQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"depth")]
        public int Depth { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool showJustificationLines { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int startBlockNumber { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MachineVerifyQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PrivateNamePreviewQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"user")]
        public byte[] User { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int nameQty { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LastFinalizedBlockQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IsFinalizedQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Hash { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BondStatusQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] publicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ExploratoryDeployQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"term")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Term { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string blockHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public bool usePreStateHash { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BondInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"validator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Validator { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"stake")]
        public long Stake { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class JustificationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"validator")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Validator { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string latestBlockHash { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeployInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"deployer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Deployer { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"term")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Term { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sig")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sig { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sigAlgorithm { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public long phloPrice { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long phloLimit { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public long validAfterBlockNumber { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"cost")]
        public ulong Cost { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"errored")]
        public bool Errored { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string systemDeployError { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LightBlockInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string blockHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"sender")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sender { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        public long seqNum { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sig")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sig { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sigAlgorithm { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string shardId { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public byte[] extraBytes { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"version")]
        public long Version { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"timestamp")]
        public long Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public byte[] headerExtraBytes { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"parentsHashList")]
        public global::System.Collections.Generic.List<string> parentsHashLists { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(12)]
        public long blockNumber { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string preStateHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string postStateHash { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15)]
        public byte[] bodyExtraBytes { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"bonds")]
        public global::System.Collections.Generic.List<BondInfo> Bonds { get; } = new global::System.Collections.Generic.List<BondInfo>();

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string blockSize { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18)]
        public int deployCount { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public float faultTolerance { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"justifications")]
        public global::System.Collections.Generic.List<JustificationInfo> Justifications { get; } = new global::System.Collections.Generic.List<JustificationInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LightBlockInfo blockInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"deploys")]
        public global::System.Collections.Generic.List<DeployInfo> Deploys { get; } = new global::System.Collections.Generic.List<DeployInfo>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DataWithBlockInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"postBlockData")]
        public global::System.Collections.Generic.List<global::dotrchain.Par> postBlockDatas { get; } = new global::System.Collections.Generic.List<global::dotrchain.Par>();

        [global::ProtoBuf.ProtoMember(2, Name = @"block")]
        public LightBlockInfo Block { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContinuationsWithBlockInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<WaitingContinuationInfo> postBlockContinuations { get; } = new global::System.Collections.Generic.List<WaitingContinuationInfo>();

        [global::ProtoBuf.ProtoMember(2, Name = @"block")]
        public LightBlockInfo Block { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WaitingContinuationInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<global::dotrchain.BindPattern> postBlockPatterns { get; } = new global::System.Collections.Generic.List<global::dotrchain.BindPattern>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::dotrchain.Par postBlockContinuation { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportProduceProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel")]
        public global::dotrchain.Par Channel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::dotrchain.ListParWithRandom Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportConsumeProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channels")]
        public global::System.Collections.Generic.List<global::dotrchain.Par> Channels { get; } = new global::System.Collections.Generic.List<global::dotrchain.Par>();

        [global::ProtoBuf.ProtoMember(2, Name = @"patterns")]
        public global::System.Collections.Generic.List<global::dotrchain.BindPattern> Patterns { get; } = new global::System.Collections.Generic.List<global::dotrchain.BindPattern>();

        [global::ProtoBuf.ProtoMember(4, Name = @"peeks")]
        public global::System.Collections.Generic.List<PeekProto> Peeks { get; } = new global::System.Collections.Generic.List<PeekProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportCommProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"consume")]
        public ReportConsumeProto Consume { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"produces")]
        public global::System.Collections.Generic.List<ReportProduceProto> Produces { get; } = new global::System.Collections.Generic.List<ReportProduceProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReportProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"produce")]
        public ReportProduceProto Produce
        {
            get => __pbn__report.Is(1) ? ((ReportProduceProto)__pbn__report.Object) : default;
            set => __pbn__report = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeProduce() => __pbn__report.Is(1);
        public void ResetProduce() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__report, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__report;

        [global::ProtoBuf.ProtoMember(2, Name = @"consume")]
        public ReportConsumeProto Consume
        {
            get => __pbn__report.Is(2) ? ((ReportConsumeProto)__pbn__report.Object) : default;
            set => __pbn__report = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeConsume() => __pbn__report.Is(2);
        public void ResetConsume() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__report, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"comm")]
        public ReportCommProto Comm
        {
            get => __pbn__report.Is(3) ? ((ReportCommProto)__pbn__report.Object) : default;
            set => __pbn__report = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeComm() => __pbn__report.Is(3);
        public void ResetComm() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__report, 3);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SingleReport : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"events")]
        public global::System.Collections.Generic.List<ReportProto> Events { get; } = new global::System.Collections.Generic.List<ReportProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeployInfoWithEventData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public DeployInfo deployInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"report")]
        public global::System.Collections.Generic.List<SingleReport> Reports { get; } = new global::System.Collections.Generic.List<SingleReport>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BlockEventInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LightBlockInfo blockInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"deploys")]
        public global::System.Collections.Generic.List<DeployInfoWithEventData> Deploys { get; } = new global::System.Collections.Generic.List<DeployInfoWithEventData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
