// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ProposeServiceV1.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace casper.v1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ProposeResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::dotrchain.ServiceError Error
        {
            get => __pbn__message.Is(1) ? ((global::dotrchain.ServiceError)__pbn__message.Object) : default;
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeError() => __pbn__message.Is(1);
        public void ResetError() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__message;

        [global::ProtoBuf.ProtoMember(2, Name = @"result")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Result
        {
            get => __pbn__message.Is(2) ? ((string)__pbn__message.Object) : "";
            set => __pbn__message = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeResult() => __pbn__message.Is(2);
        public void ResetResult() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__message, 2);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
