// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: RhoTypes.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace dotrchain
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Par : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sends")]
        public global::System.Collections.Generic.List<Send> Sends { get; } = new global::System.Collections.Generic.List<Send>();

        [global::ProtoBuf.ProtoMember(2, Name = @"receives")]
        public global::System.Collections.Generic.List<Receive> Receives { get; } = new global::System.Collections.Generic.List<Receive>();

        [global::ProtoBuf.ProtoMember(4, Name = @"news")]
        public global::System.Collections.Generic.List<New> News { get; } = new global::System.Collections.Generic.List<New>();

        [global::ProtoBuf.ProtoMember(5, Name = @"exprs")]
        public global::System.Collections.Generic.List<Expr> Exprs { get; } = new global::System.Collections.Generic.List<Expr>();

        [global::ProtoBuf.ProtoMember(6, Name = @"matches")]
        public global::System.Collections.Generic.List<Match> Matches { get; } = new global::System.Collections.Generic.List<Match>();

        [global::ProtoBuf.ProtoMember(7, Name = @"unforgeables")]
        public global::System.Collections.Generic.List<GUnforgeable> Unforgeables { get; } = new global::System.Collections.Generic.List<GUnforgeable>();

        [global::ProtoBuf.ProtoMember(11, Name = @"bundles")]
        public global::System.Collections.Generic.List<Bundle> Bundles { get; } = new global::System.Collections.Generic.List<Bundle>();

        [global::ProtoBuf.ProtoMember(8, Name = @"connectives")]
        public global::System.Collections.Generic.List<Connective> Connectives { get; } = new global::System.Collections.Generic.List<Connective>();

        [global::ProtoBuf.ProtoMember(9)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TaggedContinuation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"par_body")]
        public ParWithRandom ParBody
        {
            get => __pbn__tagged_cont.Is(1) ? ((ParWithRandom)__pbn__tagged_cont.Object) : default;
            set => __pbn__tagged_cont = new global::ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeParBody() => __pbn__tagged_cont.Is(1);
        public void ResetParBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__tagged_cont, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__tagged_cont;

        [global::ProtoBuf.ProtoMember(2, Name = @"scala_body_ref")]
        public long ScalaBodyRef
        {
            get => __pbn__tagged_cont.Is(2) ? __pbn__tagged_cont.Int64 : default;
            set => __pbn__tagged_cont = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeScalaBodyRef() => __pbn__tagged_cont.Is(2);
        public void ResetScalaBodyRef() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__tagged_cont, 2);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ParWithRandom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body")]
        public Par Body { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] randomState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PCost : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cost")]
        public ulong Cost { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListParWithRandom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pars")]
        public global::System.Collections.Generic.List<Par> Pars { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] randomState { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Var : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bound_var", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int BoundVar
        {
            get => __pbn__var_instance.Is(1) ? __pbn__var_instance.Int32 : default;
            set => __pbn__var_instance = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
        }
        public bool ShouldSerializeBoundVar() => __pbn__var_instance.Is(1);
        public void ResetBoundVar() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__var_instance, 1);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__var_instance;

        [global::ProtoBuf.ProtoMember(2, Name = @"free_var", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int FreeVar
        {
            get => __pbn__var_instance.Is(2) ? __pbn__var_instance.Int32 : default;
            set => __pbn__var_instance = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeFreeVar() => __pbn__var_instance.Is(2);
        public void ResetFreeVar() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__var_instance, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"wildcard")]
        public WildcardMsg Wildcard
        {
            get => __pbn__var_instance.Is(3) ? ((WildcardMsg)__pbn__var_instance.Object) : default;
            set => __pbn__var_instance = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
        }
        public bool ShouldSerializeWildcard() => __pbn__var_instance.Is(3);
        public void ResetWildcard() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__var_instance, 3);

        [global::ProtoBuf.ProtoContract()]
        public partial class WildcardMsg : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Bundle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body")]
        public Par Body { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool writeFlag { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public bool readFlag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Send : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"chan")]
        public Par Chan { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public global::System.Collections.Generic.List<Par> Datas { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(3, Name = @"persistent")]
        public bool Persistent { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReceiveBind : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"patterns")]
        public global::System.Collections.Generic.List<Par> Patterns { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(2, Name = @"source")]
        public Par Source { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"remainder")]
        public Var Remainder { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int freeCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BindPattern : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"patterns")]
        public global::System.Collections.Generic.List<Par> Patterns { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(2, Name = @"remainder")]
        public Var Remainder { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int freeCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ListBindPatterns : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"patterns")]
        public global::System.Collections.Generic.List<BindPattern> Patterns { get; } = new global::System.Collections.Generic.List<BindPattern>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Receive : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"binds")]
        public global::System.Collections.Generic.List<ReceiveBind> Binds { get; } = new global::System.Collections.Generic.List<ReceiveBind>();

        [global::ProtoBuf.ProtoMember(2, Name = @"body")]
        public Par Body { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"persistent")]
        public bool Persistent { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"peek")]
        public bool Peek { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int bindCount { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class New : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int bindCount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p")]
        public Par P { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"uri")]
        public global::System.Collections.Generic.List<string> Uris { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"injections")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, Par> Injections { get; } = new global::System.Collections.Generic.Dictionary<string, Par>();

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] locallyFree { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MatchCase : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pattern")]
        public Par Pattern { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"source")]
        public Par Source { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int freeCount { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Match : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public Par Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"cases")]
        public global::System.Collections.Generic.List<MatchCase> Cases { get; } = new global::System.Collections.Generic.List<MatchCase>();

        [global::ProtoBuf.ProtoMember(4)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Expr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"g_bool")]
        public bool GBool
        {
            get => __pbn__expr_instance.Is(1) ? __pbn__expr_instance.Boolean : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(1, value);
        }
        public bool ShouldSerializeGBool() => __pbn__expr_instance.Is(1);
        public void ResetGBool() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 1);

        private global::ProtoBuf.DiscriminatedUnion64Object __pbn__expr_instance;

        [global::ProtoBuf.ProtoMember(2, Name = @"g_int", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long GInt
        {
            get => __pbn__expr_instance.Is(2) ? __pbn__expr_instance.Int64 : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(2, value);
        }
        public bool ShouldSerializeGInt() => __pbn__expr_instance.Is(2);
        public void ResetGInt() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"g_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GString
        {
            get => __pbn__expr_instance.Is(3) ? ((string)__pbn__expr_instance.Object) : "";
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(3, value);
        }
        public bool ShouldSerializeGString() => __pbn__expr_instance.Is(3);
        public void ResetGString() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"g_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string GUri
        {
            get => __pbn__expr_instance.Is(4) ? ((string)__pbn__expr_instance.Object) : "";
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(4, value);
        }
        public bool ShouldSerializeGUri() => __pbn__expr_instance.Is(4);
        public void ResetGUri() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 4);

        [global::ProtoBuf.ProtoMember(25, Name = @"g_byte_array")]
        public byte[] GByteArray
        {
            get => __pbn__expr_instance.Is(25) ? ((byte[])__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(25, value);
        }
        public bool ShouldSerializeGByteArray() => __pbn__expr_instance.Is(25);
        public void ResetGByteArray() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 25);

        [global::ProtoBuf.ProtoMember(5, Name = @"e_not_body")]
        public ENot ENotBody
        {
            get => __pbn__expr_instance.Is(5) ? ((ENot)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(5, value);
        }
        public bool ShouldSerializeENotBody() => __pbn__expr_instance.Is(5);
        public void ResetENotBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"e_neg_body")]
        public ENeg ENegBody
        {
            get => __pbn__expr_instance.Is(6) ? ((ENeg)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(6, value);
        }
        public bool ShouldSerializeENegBody() => __pbn__expr_instance.Is(6);
        public void ResetENegBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"e_mult_body")]
        public EMult EMultBody
        {
            get => __pbn__expr_instance.Is(7) ? ((EMult)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(7, value);
        }
        public bool ShouldSerializeEMultBody() => __pbn__expr_instance.Is(7);
        public void ResetEMultBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"e_div_body")]
        public EDiv EDivBody
        {
            get => __pbn__expr_instance.Is(8) ? ((EDiv)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(8, value);
        }
        public bool ShouldSerializeEDivBody() => __pbn__expr_instance.Is(8);
        public void ResetEDivBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 8);

        [global::ProtoBuf.ProtoMember(9, Name = @"e_plus_body")]
        public EPlus EPlusBody
        {
            get => __pbn__expr_instance.Is(9) ? ((EPlus)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(9, value);
        }
        public bool ShouldSerializeEPlusBody() => __pbn__expr_instance.Is(9);
        public void ResetEPlusBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 9);

        [global::ProtoBuf.ProtoMember(10, Name = @"e_minus_body")]
        public EMinus EMinusBody
        {
            get => __pbn__expr_instance.Is(10) ? ((EMinus)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(10, value);
        }
        public bool ShouldSerializeEMinusBody() => __pbn__expr_instance.Is(10);
        public void ResetEMinusBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 10);

        [global::ProtoBuf.ProtoMember(11, Name = @"e_lt_body")]
        public ELt ELtBody
        {
            get => __pbn__expr_instance.Is(11) ? ((ELt)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(11, value);
        }
        public bool ShouldSerializeELtBody() => __pbn__expr_instance.Is(11);
        public void ResetELtBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 11);

        [global::ProtoBuf.ProtoMember(12, Name = @"e_lte_body")]
        public ELte ELteBody
        {
            get => __pbn__expr_instance.Is(12) ? ((ELte)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(12, value);
        }
        public bool ShouldSerializeELteBody() => __pbn__expr_instance.Is(12);
        public void ResetELteBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 12);

        [global::ProtoBuf.ProtoMember(13, Name = @"e_gt_body")]
        public EGt EGtBody
        {
            get => __pbn__expr_instance.Is(13) ? ((EGt)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(13, value);
        }
        public bool ShouldSerializeEGtBody() => __pbn__expr_instance.Is(13);
        public void ResetEGtBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 13);

        [global::ProtoBuf.ProtoMember(14, Name = @"e_gte_body")]
        public EGte EGteBody
        {
            get => __pbn__expr_instance.Is(14) ? ((EGte)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(14, value);
        }
        public bool ShouldSerializeEGteBody() => __pbn__expr_instance.Is(14);
        public void ResetEGteBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 14);

        [global::ProtoBuf.ProtoMember(15, Name = @"e_eq_body")]
        public EEq EEqBody
        {
            get => __pbn__expr_instance.Is(15) ? ((EEq)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(15, value);
        }
        public bool ShouldSerializeEEqBody() => __pbn__expr_instance.Is(15);
        public void ResetEEqBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 15);

        [global::ProtoBuf.ProtoMember(16, Name = @"e_neq_body")]
        public ENeq ENeqBody
        {
            get => __pbn__expr_instance.Is(16) ? ((ENeq)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(16, value);
        }
        public bool ShouldSerializeENeqBody() => __pbn__expr_instance.Is(16);
        public void ResetENeqBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 16);

        [global::ProtoBuf.ProtoMember(17, Name = @"e_and_body")]
        public EAnd EAndBody
        {
            get => __pbn__expr_instance.Is(17) ? ((EAnd)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(17, value);
        }
        public bool ShouldSerializeEAndBody() => __pbn__expr_instance.Is(17);
        public void ResetEAndBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 17);

        [global::ProtoBuf.ProtoMember(18, Name = @"e_or_body")]
        public EOr EOrBody
        {
            get => __pbn__expr_instance.Is(18) ? ((EOr)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(18, value);
        }
        public bool ShouldSerializeEOrBody() => __pbn__expr_instance.Is(18);
        public void ResetEOrBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 18);

        [global::ProtoBuf.ProtoMember(19, Name = @"e_var_body")]
        public EVar EVarBody
        {
            get => __pbn__expr_instance.Is(19) ? ((EVar)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(19, value);
        }
        public bool ShouldSerializeEVarBody() => __pbn__expr_instance.Is(19);
        public void ResetEVarBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 19);

        [global::ProtoBuf.ProtoMember(20, Name = @"e_list_body")]
        public EList EListBody
        {
            get => __pbn__expr_instance.Is(20) ? ((EList)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(20, value);
        }
        public bool ShouldSerializeEListBody() => __pbn__expr_instance.Is(20);
        public void ResetEListBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 20);

        [global::ProtoBuf.ProtoMember(21, Name = @"e_tuple_body")]
        public ETuple ETupleBody
        {
            get => __pbn__expr_instance.Is(21) ? ((ETuple)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(21, value);
        }
        public bool ShouldSerializeETupleBody() => __pbn__expr_instance.Is(21);
        public void ResetETupleBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 21);

        [global::ProtoBuf.ProtoMember(22, Name = @"e_set_body")]
        public ESet ESetBody
        {
            get => __pbn__expr_instance.Is(22) ? ((ESet)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(22, value);
        }
        public bool ShouldSerializeESetBody() => __pbn__expr_instance.Is(22);
        public void ResetESetBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 22);

        [global::ProtoBuf.ProtoMember(23, Name = @"e_map_body")]
        public EMap EMapBody
        {
            get => __pbn__expr_instance.Is(23) ? ((EMap)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(23, value);
        }
        public bool ShouldSerializeEMapBody() => __pbn__expr_instance.Is(23);
        public void ResetEMapBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 23);

        [global::ProtoBuf.ProtoMember(24, Name = @"e_method_body")]
        public EMethod EMethodBody
        {
            get => __pbn__expr_instance.Is(24) ? ((EMethod)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(24, value);
        }
        public bool ShouldSerializeEMethodBody() => __pbn__expr_instance.Is(24);
        public void ResetEMethodBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 24);

        [global::ProtoBuf.ProtoMember(27, Name = @"e_matches_body")]
        public EMatches EMatchesBody
        {
            get => __pbn__expr_instance.Is(27) ? ((EMatches)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(27, value);
        }
        public bool ShouldSerializeEMatchesBody() => __pbn__expr_instance.Is(27);
        public void ResetEMatchesBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 27);

        [global::ProtoBuf.ProtoMember(28, Name = @"e_percent_percent_body")]
        public EPercentPercent EPercentPercentBody
        {
            get => __pbn__expr_instance.Is(28) ? ((EPercentPercent)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(28, value);
        }
        public bool ShouldSerializeEPercentPercentBody() => __pbn__expr_instance.Is(28);
        public void ResetEPercentPercentBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 28);

        [global::ProtoBuf.ProtoMember(29, Name = @"e_plus_plus_body")]
        public EPlusPlus EPlusPlusBody
        {
            get => __pbn__expr_instance.Is(29) ? ((EPlusPlus)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(29, value);
        }
        public bool ShouldSerializeEPlusPlusBody() => __pbn__expr_instance.Is(29);
        public void ResetEPlusPlusBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 29);

        [global::ProtoBuf.ProtoMember(30, Name = @"e_minus_minus_body")]
        public EMinusMinus EMinusMinusBody
        {
            get => __pbn__expr_instance.Is(30) ? ((EMinusMinus)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(30, value);
        }
        public bool ShouldSerializeEMinusMinusBody() => __pbn__expr_instance.Is(30);
        public void ResetEMinusMinusBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 30);

        [global::ProtoBuf.ProtoMember(31, Name = @"e_mod_body")]
        public EMod EModBody
        {
            get => __pbn__expr_instance.Is(31) ? ((EMod)__pbn__expr_instance.Object) : default;
            set => __pbn__expr_instance = new global::ProtoBuf.DiscriminatedUnion64Object(31, value);
        }
        public bool ShouldSerializeEModBody() => __pbn__expr_instance.Is(31);
        public void ResetEModBody() => global::ProtoBuf.DiscriminatedUnion64Object.Reset(ref __pbn__expr_instance, 31);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ps")]
        public global::System.Collections.Generic.List<Par> Ps { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"remainder")]
        public Var Remainder { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ETuple : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ps")]
        public global::System.Collections.Generic.List<Par> Ps { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ESet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ps")]
        public global::System.Collections.Generic.List<Par> Ps { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"remainder")]
        public Var Remainder { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMap : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"kvs")]
        public global::System.Collections.Generic.List<KeyValuePair> Kvs { get; } = new global::System.Collections.Generic.List<KeyValuePair>();

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"remainder")]
        public Var Remainder { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMethod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string methodName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"target")]
        public Par Target { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"arguments")]
        public global::System.Collections.Generic.List<Par> Arguments { get; } = new global::System.Collections.Generic.List<Par>();

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] locallyFree { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"connective_used")]
        public bool ConnectiveUsed { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyValuePair : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public Par Key { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"value")]
        public Par Value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EVar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"v")]
        public Var V { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ENot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p")]
        public Par P { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ENeg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p")]
        public Par P { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EDiv : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EPlus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMinus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ELt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ELte : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EGt : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EGte : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EEq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ENeq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EAnd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EOr : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMatches : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        public Par Target { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pattern")]
        public Par Pattern { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EPercentPercent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EPlusPlus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EMinusMinus : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"p1")]
        public Par P1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"p2")]
        public Par P2 { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Connective : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"conn_and_body")]
        public ConnectiveBody ConnAndBody
        {
            get => __pbn__connective_instance.Is(1) ? ((ConnectiveBody)__pbn__connective_instance.Object) : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
        }
        public bool ShouldSerializeConnAndBody() => __pbn__connective_instance.Is(1);
        public void ResetConnAndBody() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 1);

        private global::ProtoBuf.DiscriminatedUnion32Object __pbn__connective_instance;

        [global::ProtoBuf.ProtoMember(2, Name = @"conn_or_body")]
        public ConnectiveBody ConnOrBody
        {
            get => __pbn__connective_instance.Is(2) ? ((ConnectiveBody)__pbn__connective_instance.Object) : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
        }
        public bool ShouldSerializeConnOrBody() => __pbn__connective_instance.Is(2);
        public void ResetConnOrBody() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"conn_not_body")]
        public Par ConnNotBody
        {
            get => __pbn__connective_instance.Is(3) ? ((Par)__pbn__connective_instance.Object) : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
        }
        public bool ShouldSerializeConnNotBody() => __pbn__connective_instance.Is(3);
        public void ResetConnNotBody() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"var_ref_body")]
        public VarRef VarRefBody
        {
            get => __pbn__connective_instance.Is(4) ? ((VarRef)__pbn__connective_instance.Object) : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(4, value);
        }
        public bool ShouldSerializeVarRefBody() => __pbn__connective_instance.Is(4);
        public void ResetVarRefBody() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"conn_bool")]
        public bool ConnBool
        {
            get => __pbn__connective_instance.Is(5) ? __pbn__connective_instance.Boolean : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(5, value);
        }
        public bool ShouldSerializeConnBool() => __pbn__connective_instance.Is(5);
        public void ResetConnBool() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"conn_int")]
        public bool ConnInt
        {
            get => __pbn__connective_instance.Is(6) ? __pbn__connective_instance.Boolean : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(6, value);
        }
        public bool ShouldSerializeConnInt() => __pbn__connective_instance.Is(6);
        public void ResetConnInt() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"conn_string")]
        public bool ConnString
        {
            get => __pbn__connective_instance.Is(7) ? __pbn__connective_instance.Boolean : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(7, value);
        }
        public bool ShouldSerializeConnString() => __pbn__connective_instance.Is(7);
        public void ResetConnString() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 7);

        [global::ProtoBuf.ProtoMember(8, Name = @"conn_uri")]
        public bool ConnUri
        {
            get => __pbn__connective_instance.Is(8) ? __pbn__connective_instance.Boolean : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(8, value);
        }
        public bool ShouldSerializeConnUri() => __pbn__connective_instance.Is(8);
        public void ResetConnUri() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 8);

        [global::ProtoBuf.ProtoMember(9, Name = @"conn_byte_array")]
        public bool ConnByteArray
        {
            get => __pbn__connective_instance.Is(9) ? __pbn__connective_instance.Boolean : default;
            set => __pbn__connective_instance = new global::ProtoBuf.DiscriminatedUnion32Object(9, value);
        }
        public bool ShouldSerializeConnByteArray() => __pbn__connective_instance.Is(9);
        public void ResetConnByteArray() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__connective_instance, 9);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VarRef : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"index", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Index { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"depth", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public int Depth { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectiveBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ps")]
        public global::System.Collections.Generic.List<Par> Ps { get; } = new global::System.Collections.Generic.List<Par>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeployId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sig")]
        public byte[] Sig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DeployerId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] publicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GUnforgeable : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"g_private_body")]
        public GPrivate GPrivateBody
        {
            get => __pbn__unf_instance.Is(1) ? ((GPrivate)__pbn__unf_instance.Object) : default;
            set => __pbn__unf_instance = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeGPrivateBody() => __pbn__unf_instance.Is(1);
        public void ResetGPrivateBody() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__unf_instance, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__unf_instance;

        [global::ProtoBuf.ProtoMember(2, Name = @"g_deploy_id_body")]
        public GDeployId GDeployIdBody
        {
            get => __pbn__unf_instance.Is(2) ? ((GDeployId)__pbn__unf_instance.Object) : default;
            set => __pbn__unf_instance = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeGDeployIdBody() => __pbn__unf_instance.Is(2);
        public void ResetGDeployIdBody() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__unf_instance, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"g_deployer_id_body")]
        public GDeployerId GDeployerIdBody
        {
            get => __pbn__unf_instance.Is(3) ? ((GDeployerId)__pbn__unf_instance.Object) : default;
            set => __pbn__unf_instance = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeGDeployerIdBody() => __pbn__unf_instance.Is(3);
        public void ResetGDeployerIdBody() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__unf_instance, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"g_sys_auth_token_body")]
        public GSysAuthToken GSysAuthTokenBody
        {
            get => __pbn__unf_instance.Is(4) ? ((GSysAuthToken)__pbn__unf_instance.Object) : default;
            set => __pbn__unf_instance = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeGSysAuthTokenBody() => __pbn__unf_instance.Is(4);
        public void ResetGSysAuthTokenBody() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__unf_instance, 4);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GPrivate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public byte[] Id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GDeployId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sig")]
        public byte[] Sig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GDeployerId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] publicKey { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GSysAuthToken : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
